### ISSUE TITLE
[BUG] error message format and exist code is not clear

### ISSUE THREAD

**Issue by mkindahl** [GrayJack/coreutils#100] opened 2019-10-22 05:52 UTC
**Describe the bug**

Requirements on how the error message should look is not clear and what exit code to return is not clear in `CONTRIBUTING.md`.

**To Reproduce**

Read `CONTRIBUTING.md`

**Expected behavior**

Expecting the following two points to be in `CONTRIBUTING.md`:

* That the format should be `<tool>: <message>`
* That the exit code should be 0 for successful execution, 2 for errors that indicate wrong usage, 1 for anything else (taken from http://www.tldp.org/LDP/abs/html/exitcodes.html)

**Comment by FedericoPonzi** [comment] 2019-10-22 19:59
Regarding the "expected behavior" section: 
Isn't the first point already there? (Since a while actually)
Regarding the second point, for me it's kind of obvious: since we're implementing coreutils tools the expected exit code should be the same as the original tools (which should hopefully coincide to the behavior described in the link you posted).
Does this solve your issue, or do you feel it should be more clear in the Contributing file?

**Comment by GrayJack** [comment] 2019-10-23 02:30
For me the part of the exit code was clear to me that should be the same as the original tools
About the message format, I also thought it was clear, since all original tools use it

**Comment by mkindahl** [comment] 2019-10-23 05:56
Well... it is good to be clear on these issues in anything involving more than one person. Remember that in a room with developers there it at least as many different opinions as developers. ;)

Now, this is the text before Eric's change:

```
### Tools Styleguide
* Always use `clap` with `yaml` support to create the tools arguments.
* Always create a `build.rs` that creates every shell completions.
* Every argument have to have the `help` text.
* Every parameter have to have the `long` and `short` options.
```

There is nothing about the error message from the tool or exit code (the text above only covers commit messages). The text after Eric's change is what I expected.

**Comment by GrayJack** [comment] 2019-10-23 18:57
So can I close this?

**Comment by mkindahl** [comment] 2019-10-23 21:38
Absolutely. :)

**Closed** 2019-10-23 21:39 UTC
Labels: bug
